### ISSUE TITLE
Allow to_json to return maps instead of proplists.

### ISSUE THREAD

**Issue by lordnull** [lordnull/rec2json#22]
Maps represent a json object more performantly than proplists. Furthermore, checking for an empty object avoids the ugly `[{}]` hack. However, backwards compatibility is desirable, so we can't just swap, at least not without a major version change.

The options are:
- Use a -d macro check to allow all rec2json transformed modules to use maps or not, thus altering an entire project at once.
- use the -rec2json attribute and place an option there to switch use of maps on an individual module basis

**Comment by jairov4** [comment]
I would love this

**Comment by jairov4** [comment]
Hey there, It looks very promising, I am testing the latest v4.0.0 but unfortunely I found issues calling `from_json()`.

Im always getting 

```
** exception error: no function clause matching account_product:scrub_keys(#{code => <<"c">>,expiration_date => <<"d">>},[])
```

Im using the simplest declaration:

```erlang
-record(account_product, {
    code :: binary(),
    expiration_date :: binary()
}).
```

I was on Erlang 19.1 with Rebar3 using the line as:
```
{rec2json, {git, "https://github.com/lordnull/rec2json.git", {tag, "4.0.0"}}},
```

**Comment by lordnull** [comment]
I've attempted to replicate your issue on Erlang 19.1 on OS 10.13.1 with tag 4.0.0 using the exact record you provided. I get no error, I get the record as documented indicates I should.

Looking at the error, I would guess that an old version of rec2json is being used. The scrub_keys function is no longer added to the transformed module (to reduce the possibility of a function name collision). If the module were transformed with 4.0.0, the scrub_keys would not exist to be called. If 4.0.0 were not loaded when using from_json/1, the scrub keys would never be called.

Perhaps rec2json did not get rebuilt?

**Comment by jairov4** [comment]
Thanks for try replicate it, It was weird that I got not rebuilt because I was aware of that kind of issues in rebar3 but anyways may be I forgot some step. I will check it again

**Comment by lordnull** [comment]
Were you able to resolve this?

**Comment by lordnull** [comment]
Closing as there's been no movement on this in over a month. I'm going to assume resolved.
