### ISSUE TITLE
Unprocessed error

### ISSUE THREAD

**Issue by vipinsingh211** [lordnull/rec2json#28]
Trying to convert below record to json:
```erlang
#eth{src = "00:50:56:C0:00:08",dst = "01:00:5E:00:00:FB",
     type = ipv4,
     data = #ipv4{vsn = 4,hlen = 5,diffserv = 0,totlen = 73,
                  id = 17452,flags = [],frag_offset = 0,ttl = 255,proto = udp,
                  hdr_csum = correct,
                  src = <<172,16,216,1>>,
                  dst = <<224,0,0,251>>,
                  options = [],
                  data = #udp{src_port = <<"mdns">>,dst_port = <<"mdns">>,
                              length = 53,csum = correct,
                              data = [{dns_header,0,0,0,0,0,0,0,0,0},
                                      [{dns_query,"_ipp._tcp.local",ptr,in},
                                       {dns_query,"_ipps._ipps._tcp.local",ptr,in}],
                                      [],[],[]]}}}
```

But getting below error:
```error
Unprocessed: eth,to_json,[{eth,"00:50:56:C0:00:08","01:00:5E:00:00:FB",ipv4,{ipv4,4,5,0,73,17452,[],0,255,udp,correct,<<172,16,216,1>>,<<224,0,0,251>>,[],{udp,<<"mdns">>,<<"mdns">>,53,correct,[{dns_header,0,0,0,0,0,0,0,0,0},[{dns_query,"_ipp._tcp.local",ptr,in},{dns_query,"_ipps._ipps._tcp.local",ptr,in}],[],[],[]]}}}],[]
```

**Comment by lordnull** [comment]
I've attached a module I whipped up to see if I could reproduce, but it outputs a prop list as I would expect with an untyped record:

[eth.erl.txt](https://github.com/lordnull/rec2json/files/1042744/eth.erl.txt)

The <pre>doit/0</pre> function outputs:

    12> c("eth.erl").
    {ok,eth}
    13> eth:doit().
    [{src,"00:50:56:C0:00:08"},
     {dst,"01:00:5E:00:00:FB"},
     {type,<<"ipv4">>},
     {data,{ipv4,4,5,0,73,17452,[],0,255,udp,correct,
                 <<172,16,216,1>>,
                 <<224,0,0,251>>,
                 [],
                 {udp,<<"mdns">>,<<"mdns">>,53,correct,
                      [{dns_header,...},[...]|...]}}}]

Essentially a prop list that has no conversions applied outside of the built-in ones.

What is the exact function call that is proceeding the "Unprocessed" message? How are the eth, ipv4, and upd records defined and typed?

**Comment by vipinsingh211** [comment]
Thanks, I was missing to declare the records. Now it is working for me. 👍
