### ISSUE TITLE
Possible Error

### ISSUE THREAD

**Issue by protostartup** [lordnull/rec2json#30]
Hi, 
   In context of  "Json to record"  what if I don't have a field that is specified in the record definition. How can I handle these scenario.

Am having an application which sends a very large Json, I try to minimize the size by deleting some fields of the Json depending on the operation. So even though I use the same Json definition some fields may be missing. 

Any suggestion for the problem would be highly appreciable

**Comment by lordnull** [comment]
rec2json will use the default value of the record if the field is missing from the json; or if you provide a 'base' record to the 'from_json' record, the value will be used. I do a similar tactic in my software.

```erlang
-record(person, {
    name :: binary(),
    birth_year = 1970 :: pos_integer()
}).

missing_name() ->
    Json = [{<<"birth_year">>, 2012}],
    #person{name = undefined} = from_json(Json),
    #person{name = <<"batman">>} = from_json(Json, #person{name = <<"batman">>}).

missing_age() ->
    Json = [{<<"name">>, <<"superman">>}],
    #person{birth_year = 1970} = from_json(Json),
    #person{birth_year = 2012} = from_json(Json, #person{birth_year = 2012}).
```
